ARTISTS = [
    {
        "id": 'ap-dhillon',
        "name": 'AP Dhillon',
        "spotify_id": '5fMUXHkw8R8eOP2RNVYEZX',
        "youtube_channel_id": 'UCSyLjhUyyVMIPK4MZGO7oIA',
        "genre": 'Punjabi',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'karan-aujla',
        "name": 'Karan Aujla',
        "spotify_id": '6DARBhWjJnXIFJXqwv0yW2',
        "youtube_channel_id": 'UCN_FB1EAzJnYes92BOUFhhg',
        "genre": 'Punjabi',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'jasmine-sandlas',
        "name": 'Jasmine Sandlas',
        "spotify_id": '2Xme2bK3HgzSxQPf93fZCH',
        "youtube_channel_id": 'UC_MZXG6ePLkJLzh-RxlFojw',
        "genre": 'Punjabi',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'garry-sandhu',
        "name": 'Garry Sandhu',
        "spotify_id": '7EPsAJSPQf1O4hgizLsMti',
        "youtube_channel_id": 'UCcYiNDPaUNx8sEJMJJAkFvw',
        "genre": 'Punjabi',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'shubh',
        "name": 'Shubh',
        "spotify_id": '0Cfkvk0dOEfwdAr8EAAGME',
        "youtube_channel_id": 'UCWwPe_SnYkxnOICvcPovVyA',
        "genre": 'Punjabi',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'mc-stan',
        "name": 'MC STΔN',
        "spotify_id": '1qFp8QxHGxs3GlGPvdkJ8o',
        "youtube_channel_id": 'UC0JkdZnxVfibnxTix1JPULQ',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'king',
        "name": 'King',
        "spotify_id": '6l3HvQ5sa6mXTsMTB19rO5',
        "youtube_channel_id": 'UC-JFyL0zDFOsPMpS2dVKDIw',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 1,
    },
    {
        "id": 'emiway-bantai',
        "name": 'Emiway Bantai',
        "spotify_id": '3ievSeITpO7psxFBFp6uA7',
        "youtube_channel_id": 'UCx4bFGMIBQLqTeLEsHNBbMQ',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'kr$na',
        "name": 'KRSNA',
        "spotify_id": '275e2m1Ln7ND66CtLPPKSz',
        "youtube_channel_id": 'UCuLhJT5cmLEIMC-Hyp_Rerg',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'prabh-deep',
        "name": 'Prabh Deep',
        "spotify_id": '7rHXbsEJoASYSs3QWudqey',
        "youtube_channel_id": 'UCQ3MKSUUdCPBqHsLPd7DdBQ',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'dino-james',
        "name": 'Dino James',
        "spotify_id": '7HiIkf5zyQWOJyhDw61b3j',
        "youtube_channel_id": 'UC1i0MmP8X01B30sa4yLDnOQ',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'talha-anjum',
        "name": 'Talha Anjum',
        "spotify_id": '1P3oAIVcCsGdGINNBb3D6Q',
        "youtube_channel_id": 'UCz3hCgHqc1p6qL2y3J2MvCA',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'prateek-kuhad',
        "name": 'Prateek Kuhad',
        "spotify_id": '6WpVpHTf9tdi15XwjkNiSY',
        "youtube_channel_id": 'UCSLFfA7UdHcMb9aaL78wc8Q',
        "genre": 'Indie',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'anuv-jain',
        "name": 'Anuv Jain',
        "spotify_id": '3tJoFztHeIJkHXMdOkbqAb',
        "youtube_channel_id": 'UCmAX1TwVPMIO7ACsmF5ISSA',
        "genre": 'Indie',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'ritviz',
        "name": 'Ritviz',
        "spotify_id": '3qnGvpP8Yth1AqSBMqON5x',
        "youtube_channel_id": 'UCmh2xaRVJkfXGA7e6U1mx7Q',
        "genre": 'Indie/Electronic',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'when-chai-met-toast',
        "name": 'When Chai Met Toast',
        "spotify_id": '28kcGLwxLfzCIuK0P0SIJ0',
        "youtube_channel_id": 'UCIeBWObZFt_Dv3ZhYjTqjhg',
        "genre": 'Indie',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'the-local-train',
        "name": 'The Local Train',
        "spotify_id": '7nBXaUwuVj4V6QNPWWDqDi',
        "youtube_channel_id": 'UCb1bT0t3Mm4TDGJUXMzsoiQ',
        "genre": 'Indie Rock',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'nucleya',
        "name": 'Nucleya',
        "spotify_id": '0UMffqXaiBLGoPV0F5IIYL',
        "youtube_channel_id": 'UCQGQEQK5XEjaFI4VMHX9yg',
        "genre": 'Electronic',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'taba-chake',
        "name": 'Taba Chake',
        "spotify_id": '0W78w7OZ7fk3UkK3fLnVJK',
        "youtube_channel_id": 'UCzBhxfCkJ3IgYU17bZlX8Vg',
        "genre": 'Indie Folk',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'ankur-tewari',
        "name": 'Ankur Tewari',
        "spotify_id": '4nP5UA5wm0LkIFHqHO6P7a',
        "youtube_channel_id": 'UCwh7tmv2Yv4E1XcNYaV2Yng',
        "genre": 'Indie',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'sapna-choudhary',
        "name": 'Sapna Choudhary',
        "spotify_id": '0EFisYRi1XOefXCmfrM3UZ',
        "youtube_channel_id": 'UCTr9CSCMG9SjNjJi0UhRFkw',
        "genre": 'Haryanvi',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'gulzaar-chhaniwala',
        "name": 'Gulzaar Chhaniwala',
        "spotify_id": '2SHfUeh7gw3LDgjxyT0bxV',
        "youtube_channel_id": 'UCFe-EFkXIYelQcvn5M0HXAw',
        "genre": 'Haryanvi',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'anupam-roy',
        "name": 'Anupam Roy',
        "spotify_id": '1SJOL9HJ08YOn92lFcYf8a',
        "youtube_channel_id": 'UCh1gVPb7_IkKZ84Zy79J76Q',
        "genre": 'Bengali',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'arijit-singh-bengali',
        "name": 'Rupam Islam',
        "spotify_id": '66ZVo4kYEZN37t4AKXLqmM',
        "youtube_channel_id": 'UCjMGJu4aYuIs6BTnTkp97Xw',
        "genre": 'Bengali Rock',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'mc-square',
        "name": 'MC Square',
        "spotify_id": '7iPDkJYZHy0KHCR4B1sJpV',
        "youtube_channel_id": 'UCK-bHPOGn-lGBk9slquIsNQ',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'riar-saab',
        "name": 'Riar Saab',
        "spotify_id": '3CLJaJWZPpgGL7CnAhMiCS',
        "youtube_channel_id": 'UC8mcEboBhR_kU5Kkq1S4IIQ',
        "genre": 'Punjabi',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'hanumankind',
        "name": 'Hanumankind',
        "spotify_id": '0G0j0q0q0q0q0q0q0q0q0q',
        "youtube_channel_id": 'UC5G0Th3UCJL5OkxOTgZhECA',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'fotty-seven',
        "name": 'Fotty Seven',
        "spotify_id": '59R9jU69KJFfmkUYuqFUQi',
        "youtube_channel_id": 'UCDhv8_xtNwmCrROPRNfLsbg',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'raga',
        "name": 'Raga',
        "spotify_id": '5FnYvRvJpe4T03cq9OVS3a',
        "youtube_channel_id": 'UCddqrmJN7eVJ30qmHU6Rntg',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'bella',
        "name": 'Bella',
        "spotify_id": '0W78w7OZ7fk3UkK3fLnVJL',
        "youtube_channel_id": 'UCaRQ-P-4nfLMawBhzO2vxHg',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'dakait',
        "name": 'Dakait',
        "spotify_id": '1qFp8QxHGxs3GlGPvdkJ8p',
        "youtube_channel_id": 'UC0zT-sXLfwE1Hfkqes7J6Dw',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'yashraj-mukhate',
        "name": 'Yashraj Mukhate',
        "spotify_id": '6lNF9u8WvnlCG9YeSHmO3R',
        "youtube_channel_id": 'UCcfcOcnXMHjHKOKOJO2w08g',
        "genre": 'Viral/Pop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'kaifi-khalil',
        "name": 'Kaifi Khalil',
        "spotify_id": '6KESsBnJkAGIU5nqmBjPQ2',
        "youtube_channel_id": 'UC6zO45sGu1P6qGlbF490mIA',
        "genre": 'Sufi/Pop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'speed-records',
        "name": 'Speed Records',
        "spotify_id": None,
        "youtube_channel_id": 'UCL5bKKRdqhqjcqNOldL5CBg',
        "genre": 'Label',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'ali-zafar',
        "name": 'Ali Zafar',
        "spotify_id": '3cKNppGLfcxdt9CtoHEZmQ',
        "youtube_channel_id": None,
        "genre": 'Pop/Sufi',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb7c318b35e3be48fe8f5a0a38',
        "is_watched": 0,
    },
    {
        "id": 'tanishka-bahl',
        "name": 'Tanishka Bahl',
        "spotify_id": '0RZSHotYnUAsA9mzApotQw',
        "youtube_channel_id": None,
        "genre": 'Indie',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb38449138ef884b9e234b1bba',
        "is_watched": 1,
    },
    {
        "id": 'edens-echo',
        "name": 'Edens Echo',
        "spotify_id": '1ahi91QGWacjQieauSdApk',
        "youtube_channel_id": None,
        "genre": 'Indie',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'arooh',
        "name": 'Arooh',
        "spotify_id": '3E9wPDeQ4FoB8okbcGF0Q7',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb85150e4b86886cb03994c54e',
        "is_watched": 0,
    },
    {
        "id": 'bagghe-smg',
        "name": 'Bagghe SMG',
        "spotify_id": '4eu7AyzvnafwOygTQlfAMu',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebe7c702f5b891874916f3d0b5',
        "is_watched": 0,
    },
    {
        "id": 'bhoomi',
        "name": 'Bhoomi',
        "spotify_id": '0gMaH5l7qBDky1LyM6ELYS',
        "youtube_channel_id": None,
        "genre": 'Indie',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb3103b6a90f2b976c1f704bd6',
        "is_watched": 1,
    },
    {
        "id": 'talwiinder',
        "name": 'Talwiinder',
        "spotify_id": '6QoCrBHsojKnOrsGNfRcTN',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop/R&B',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb3966ca5f9b36d4a5d3d7f6b1',
        "is_watched": 0,
    },
    {
        "id": 'gunda',
        "name": 'Gunda',
        "spotify_id": '7qviR9RWRL1V3aM0yQ8V0D',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebaabffc7571a688b2fe287453',
        "is_watched": 0,
    },
    {
        "id": 'shashxnk',
        "name": 'Shashxnk',
        "spotify_id": '3LUBREkWFY59KQ3t5Oq5ji',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb4ec07e77cbade76772667f03',
        "is_watched": 0,
    },
    {
        "id": 'lekhak',
        "name": 'Lekhak',
        "spotify_id": '7EzXvSTOIXrtaL87k7aoBG',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebe302a21b3357716f898151f6',
        "is_watched": 0,
    },
    {
        "id": 'niraj-chag',
        "name": 'Niraj Chag',
        "spotify_id": '0GcVFL5IbFUWK4qj1ZNxk6',
        "youtube_channel_id": None,
        "genre": 'Indie/Electronic',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb1185b923d56b6ed217a186f1',
        "is_watched": 0,
    },
    {
        "id": 'salem-sandhu',
        "name": 'Salem Sandhu',
        "spotify_id": '0Eh7Sz5p4UQ6AfOcFu5f45',
        "youtube_channel_id": None,
        "genre": 'Punjabi',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb61a5e9d90cd454e49e6cee8f',
        "is_watched": 0,
    },
    {
        "id": 'firaaq',
        "name": 'Firaaq',
        "spotify_id": '3souTM6F1BIoqEaLRDfaGc',
        "youtube_channel_id": None,
        "genre": 'Indie',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb413f350f4be1a70146988b99',
        "is_watched": 0,
    },
    {
        "id": 'mitraz',
        "name": 'Mitraz',
        "spotify_id": '3iGhlvzpXc0UHBQ7klAItX',
        "youtube_channel_id": 'UCewyFby3pwB31EPE1PpCT1Q',
        "genre": 'Indie',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebe96a339b04840c8fb801ccb4',
        "is_watched": 0,
    },
    {
        "id": 'pradheep',
        "name": 'Pradheep',
        "spotify_id": '3IHEvRZ9nupY9hVU6SBLVc',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab67616d0000b273d0e30d5cc68803c15b268c5a',
        "is_watched": 0,
    },
    {
        "id": 'sez-on-the-beat',
        "name": 'Sez On the Beat',
        "spotify_id": '7hI0IRD66iykVpXiieNRbe',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop/Producer',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb11dd495fb18ccc4feebf36a1',
        "is_watched": 0,
    },
    {
        "id": 'chaar-diwari',
        "name": 'Chaar Diwari',
        "spotify_id": '2n4q8jLM4WLwlva1sZ2WRx',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb7893d3d72cd3b06791652580',
        "is_watched": 0,
    },
    {
        "id": 'bali',
        "name": 'Bali',
        "spotify_id": '65pmgBULHr82D3llNlHtB8',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb91e77b3b45c2e8380d445665',
        "is_watched": 0,
    },
    {
        "id": 'enzo',
        "name": 'Enzo',
        "spotify_id": '0QX0UY2UJtnhfEbqUbTz6h',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb8829fd45300dbda57450f725',
        "is_watched": 0,
    },
    {
        "id": 'himonshu',
        "name": 'Himonshu',
        "spotify_id": '0AHysaqWv1LHwqk5P5lTMX',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb09d1425b729b2c64e69320b1',
        "is_watched": 0,
    },
    {
        "id": 'kushagra-thakur',
        "name": 'Kushagra Thakur',
        "spotify_id": '42goWWrEkKtOFzVu88jwpn',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab67616d0000b2733f7d9b4fdd1c5111a1db70a6',
        "is_watched": 0,
    },
    {
        "id": 'showkid',
        "name": 'Showkid',
        "spotify_id": '0Jm1jErRgViI7B3mJ5J76V',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab67616d0000b273d06ded5256aa86e83270ced5',
        "is_watched": 0,
    },
    {
        "id": 'natkhat',
        "name": 'Natkhat',
        "spotify_id": '6CzAKvrlzl1z9U2WPvY4VA',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebf06a48eb3c1ad9d54be8daf8',
        "is_watched": 0,
    },
    {
        "id": 'bad-krazy',
        "name": 'Bad krazy',
        "spotify_id": '1qieuQ4mdiFSY8iVEtoPW1',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebc56f75cb9026a2de0a769c01',
        "is_watched": 0,
    },
    {
        "id": 'hurricane',
        "name": 'Hurricane',
        "spotify_id": '6OvPeLnrLk4v7X7tmjnOiO',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebaa1e4f2269f6f105e6891984',
        "is_watched": 0,
    },
    {
        "id": 'dl91-era',
        "name": 'DL91 Era',
        "spotify_id": '3mWqCmX0xuzBJN648XSBrE',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebef0b0a24b4754e838f07ee71',
        "is_watched": 1,
    },
    {
        "id": 'zehr-vibe',
        "name": 'Zehr Vibe',
        "spotify_id": '48cVwD5hffidwvlxLCc2pm',
        "youtube_channel_id": None,
        "genre": 'Punjabi',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebec41fd2f0173b6a2d6643a1e',
        "is_watched": 0,
    },
    {
        "id": 'intense',
        "name": 'Intense',
        "spotify_id": '0OS0NZnK7TGIAWx8MkWNFN',
        "youtube_channel_id": None,
        "genre": 'Punjabi/Producer',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb01b588c38c72cc46adf28ab3',
        "is_watched": 1,
    },
    {
        "id": 'vilen',
        "name": 'Vilen',
        "spotify_id": '5gVozagAcRKYCeAVnlC3Nk',
        "youtube_channel_id": None,
        "genre": 'Indie/Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebc02a4d641eba9b253e106733',
        "is_watched": 0,
    },
    {
        "id": 'rumii',
        "name": 'Rumii',
        "spotify_id": '72mOygqSqfOoHLiiL9s7ig',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb565b3ceb2f9b624987ca5af7',
        "is_watched": 0,
    },
    {
        "id": 'chayan',
        "name": 'Chayan',
        "spotify_id": '7unUdPbyPyy71g6WeD0M4U',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb21cf4214bae20ddfdcaf6ff6',
        "is_watched": 0,
    },
    {
        "id": 'the-ranjha',
        "name": 'The Ranjha',
        "spotify_id": '23gh7bRgR4erlbpfArCjOF',
        "youtube_channel_id": None,
        "genre": 'Punjabi',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebece87e9da20d8b3b486ed25d',
        "is_watched": 0,
    },
    {
        "id": 'aur',
        "name": 'AUR',
        "spotify_id": '2cjQTf2J5yCaNY8qHpW855',
        "youtube_channel_id": None,
        "genre": 'Indie/Pop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebd3285f46d890c938885f499c',
        "is_watched": 0,
    },
    {
        "id": 'karma',
        "name": 'Karma',
        "spotify_id": '2RS1R0tueoL8EJXTSBAt2F',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebec5399c902437e0594d8ab07',
        "is_watched": 0,
    },
    {
        "id": 'vasu-raina',
        "name": 'Vasu Raina',
        "spotify_id": '5wwyvQQMsmzSUZo6FBoWJL',
        "youtube_channel_id": None,
        "genre": 'Indie',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb71353aefebd9054f413413cb',
        "is_watched": 0,
    },
    {
        "id": 'kushagra',
        "name": 'Kushagra',
        "spotify_id": '2IKfr1JgPRXmXKAWwrABc6',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb36727564ac48444dd9dfcb3b',
        "is_watched": 0,
    },
    {
        "id": 'showkidd',
        "name": 'Showkidd',
        "spotify_id": '0lqjRojARBHXCBYVOm16CC',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb4de40abacf7afd90a21378da',
        "is_watched": 0,
    },
    {
        "id": 'saaheal',
        "name": 'Saaheal',
        "spotify_id": '29S4JzoFUP1MCyMgKd83zM',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb3567c18bcfc0e8ce0db63055',
        "is_watched": 0,
    },
    {
        "id": 'hrjxt',
        "name": 'HRJXT',
        "spotify_id": '4s5P33ladNMi7gcBMHwp9a',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop/Producer',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebffea8e0094c43eebc719d11b',
        "is_watched": 0,
    },
    {
        "id": 'kmrn',
        "name": 'KMRN',
        "spotify_id": '6qilOLk8soI4DjjM2wZlO1',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb42507c717461acd0eb04988d',
        "is_watched": 0,
    },
    {
        "id": 'wamp',
        "name": 'Wamp',
        "spotify_id": '6zpUQnCceOC1hkBQWLrZKk',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebcec9cd5caf00d55682c47350',
        "is_watched": 0,
    },
    {
        "id": 'cloonee',
        "name": 'Cloonee',
        "spotify_id": '7MdlXmq2HViAJWo9cf30sR',
        "youtube_channel_id": None,
        "genre": 'Electronic',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebd0c97bcaa85830ce5f882f0e',
        "is_watched": 0,
    },
    {
        "id": 'mizajiii',
        "name": 'Mizajiii',
        "spotify_id": '3Y70kiqHFQIjL0ILb40YCO',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebb6fb9c7205029f64729dcec2',
        "is_watched": 0,
    },
    {
        "id": 'ranj',
        "name": 'Ranj',
        "spotify_id": '7pqzMLbLDB5UFg9LM0y9im',
        "youtube_channel_id": None,
        "genre": 'Punjabi',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb496e4d8b0f818845be7acc5a',
        "is_watched": 0,
    },
    {
        "id": 'harkirat-sangha',
        "name": 'Harkirat Sangha',
        "spotify_id": '1fhomnuqkIYFeXNoJB5DjT',
        "youtube_channel_id": None,
        "genre": 'Punjabi',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebc88a25a5c35db8d0b2a67f9c',
        "is_watched": 0,
    },
    {
        "id": 'starboy-x',
        "name": 'Starboy X',
        "spotify_id": '0Fvud1OrUvlMHqxbEGmtnj',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb039f91b4d88f15c731a90636',
        "is_watched": 0,
    },
    {
        "id": 'shyko-music',
        "name": 'Shyko Music',
        "spotify_id": '11R9W9iHp8Z1uc6uqX4wCr',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb7350d395640a177301425979',
        "is_watched": 0,
    },
    {
        "id": 'jj47',
        "name": 'JJ47',
        "spotify_id": '1SlrUQlFRfExXSCkHsQgBc',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb25246f5e57906dc47e48530e',
        "is_watched": 0,
    },
    {
        "id": 'zellix',
        "name": 'Zellix',
        "spotify_id": '5CJ8Xtvv57oEiRKIy6OjJt',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb6d98cc49ab11474b5f139d96',
        "is_watched": 0,
    },
    {
        "id": 'real-boss',
        "name": 'Real Boss',
        "spotify_id": '7mAbpafXc2MIAZn4ldxEuP',
        "youtube_channel_id": None,
        "genre": 'Punjabi',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb1ceb1611c5348a2ef2342dfb',
        "is_watched": 0,
    },
    {
        "id": 'nehal-naseem',
        "name": 'Nehal Naseem',
        "spotify_id": '6YSVUxXGsQQD2cWSJhN8re',
        "youtube_channel_id": None,
        "genre": 'Independent',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb2f015c99431b2542b19039a6',
        "is_watched": 0,
    },
    {
        "id": 'albela',
        "name": 'Albela',
        "spotify_id": '5LAqES7mtiAF86N0aBLqPO',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb87eaf451e4c14f62c41c7a2f',
        "is_watched": 0,
    },
    {
        "id": 'raf-sappera',
        "name": 'Raf Sappera',
        "spotify_id": '182srEbrmnlFxcwkqZ0NR6',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop/Folk',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb010ad51b45434aa0e718f036',
        "is_watched": 0,
    },
    {
        "id": 'adnan-dhool',
        "name": 'Adnan Dhool',
        "spotify_id": '4XTiRlcZr4ACFHAXgV34Sc',
        "youtube_channel_id": None,
        "genre": 'Independent',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb7d373a0bd928b703e043a96b',
        "is_watched": 0,
    },
    {
        "id": 'jind-universe',
        "name": 'Jind Universe',
        "spotify_id": '5KmFbbptaZhEtmMibvibUE',
        "youtube_channel_id": None,
        "genre": 'Punjabi',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb84ceb8cfa980a212241381ef',
        "is_watched": 0,
    },
    {
        "id": 'script',
        "name": 'Script',
        "spotify_id": '4CvDmoy5yE6L4hdBOHg1sz',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb5c675590fcb927803179ce25',
        "is_watched": 0,
    },
    {
        "id": 'natiq',
        "name": 'Natiq',
        "spotify_id": '4hTKmmAjtobKYm3DJJuSkL',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb25aaa6a3d6432adff50172cc',
        "is_watched": 0,
    },
    {
        "id": 'gravero',
        "name": 'Gravero',
        "spotify_id": '0g4FyrO2K2vs07oAwWraAj',
        "youtube_channel_id": None,
        "genre": 'Electronic',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb54747e884312662a52f09a3f',
        "is_watched": 0,
    },
    {
        "id": 'faizal',
        "name": 'faizal',
        "spotify_id": '3iMtnIUSnojtxLhlP294k4',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb6d247dc84febd9db40604bd6',
        "is_watched": 0,
    },
    {
        "id": 'manish-manral',
        "name": 'Manish Manral',
        "spotify_id": '2vC797VK3xLQ12eObqvemP',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb451cdc0b29b03ca3477440ce',
        "is_watched": 0,
    },
    {
        "id": 'partiboi69',
        "name": 'partiboi69',
        "spotify_id": '0CutULGVZ24wOr1HHYoEOL',
        "youtube_channel_id": None,
        "genre": 'Electronic',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebd9c94fdcbbe9d178396d5c0d',
        "is_watched": 0,
    },
    {
        "id": 'juicy-romance',
        "name": 'Juicy Romance',
        "spotify_id": '55RZaB7LJnx3sXeyVJXB2e',
        "youtube_channel_id": None,
        "genre": 'Electronic',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb4491564ac1dc626376589e54',
        "is_watched": 0,
    },
    {
        "id": 'bir',
        "name": 'bir',
        "spotify_id": '3R1penrqtuKNTeWABjKT5N',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebf20408fe565eba0b220b6444',
        "is_watched": 0,
    },
    {
        "id": 'daaku',
        "name": 'daaku',
        "spotify_id": '0Gk0DXsojuXvKXROsCbO0e',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb9fafb8d3e87f9f7ace00d865',
        "is_watched": 0,
    },
    {
        "id": 'faizan',
        "name": 'Faizan',
        "spotify_id": '4SG1sBze1PccNVkHhX4H4x',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebe5f59275851316b783e01738',
        "is_watched": 0,
    },
    {
        "id": 'tushar-nagar',
        "name": 'Tushar Nagar',
        "spotify_id": '7h6YMcFApPh0ritIF87ygS',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebd48c020ed4739a44d39ed9ee',
        "is_watched": 0,
    },
    {
        "id": 'domboi',
        "name": 'DOMBOI',
        "spotify_id": '3IGnos0JIHmcXYF4yESCZP',
        "youtube_channel_id": None,
        "genre": 'Electronic',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebda1da4b19f60b4364dbeaf55',
        "is_watched": 0,
    },
    {
        "id": 'sinaash',
        "name": 'Sinaash',
        "spotify_id": '1NOuodJ2U1hMvKYXFJPw5P',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb74dc1f5391604b96162bf0fe',
        "is_watched": 0,
    },
    {
        "id": 'hashim-nawaz',
        "name": 'Hashim Nawaz',
        "spotify_id": '2zurwnLzcPvY8n3jJEse5E',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb17e61b19361af0e74757335b',
        "is_watched": 0,
    },
    {
        "id": 'ink-heart',
        "name": 'Ink Heart',
        "spotify_id": '010tbxYFwrOC8Nl2paePR6',
        "youtube_channel_id": None,
        "genre": 'Indie',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebb4d4fe8e302c23d2f2107e2f',
        "is_watched": 0,
    },
    {
        "id": 'tricksingh',
        "name": 'tricksingh',
        "spotify_id": '3xvOoFJqHTgdPqUVWlRYQk',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb2e10611280ab20b0302e95e6',
        "is_watched": 0,
    },
    {
        "id": 'parvaaz',
        "name": 'parvaaz',
        "spotify_id": '6vwSAnfnlO6Sy37KubGrLh',
        "youtube_channel_id": None,
        "genre": 'Indie Rock',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebcf397c5623fe77d006a6aa97',
        "is_watched": 0,
    },
    {
        "id": 'urban-poet',
        "name": 'Urban Poet',
        "spotify_id": '5NLpRU1nXHu9TnrqgXPPRM',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb0ab28561caa37522fe82b87e',
        "is_watched": 0,
    },
    {
        "id": 'noor',
        "name": 'Noor',
        "spotify_id": '7F5LO6TFFBGkRhsQdCcLVm',
        "youtube_channel_id": None,
        "genre": 'Independent',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb83f57180c86c5a7aa2276ad0',
        "is_watched": 0,
    },
    {
        "id": 'khan',
        "name": 'Khan',
        "spotify_id": '2qqPV8ZkTpVdwfMOKSsb8N',
        "youtube_channel_id": None,
        "genre": 'Independent',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb57d46cabd3f1abd2e5095f32',
        "is_watched": 0,
    },
    {
        "id": 'madhurxo',
        "name": 'Madhurxo',
        "spotify_id": '0o5KaItv2mU6ACmRP19Qc2',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb52d005442f331096e15c8eb8',
        "is_watched": 0,
    },
    {
        "id": 'dhanji',
        "name": 'Dhanji',
        "spotify_id": '1OVeQPd27s1MkICbzBfZTV',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb798042a623da483868ccbc9d',
        "is_watched": 0,
    },
    {
        "id": 'kinari',
        "name": 'Kinari',
        "spotify_id": '01QVuoMsgA0rer1H2JKuo1',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebaeaa32da14b7be96e6e05ce9',
        "is_watched": 0,
    },
    {
        "id": 'reble',
        "name": 'Reble',
        "spotify_id": '3MsxNLVtDVGxjEaxgKAoi0',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebf43b173d37b8cc00df37e804',
        "is_watched": 0,
    },
    {
        "id": 'lashcurry',
        "name": 'Lashcurry',
        "spotify_id": '0ZqtJiXuNMU9NPF1cEef1T',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab67616d0000b273a219adff7d7389fc40cbec3c',
        "is_watched": 0,
    },
    {
        "id": 'loka',
        "name": 'Loka',
        "spotify_id": '0AK5uxL2fY52xEoj1bBySu',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb7ca4a80609ba46bb6258a9da',
        "is_watched": 0,
    },
    {
        "id": 'tienas',
        "name": 'Tienas',
        "spotify_id": '6JvFJaw7uRQFBUzSlv28Gw',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb80fa928b04f3313fe6af7608',
        "is_watched": 0,
    },
    {
        "id": 'smokey-the-ghost',
        "name": 'Smokey The Ghost',
        "spotify_id": '3P4yYdpOTSa94saSCZja7s',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb9a76b0459e35fe6347014641',
        "is_watched": 0,
    },
    {
        "id": 'boyblanck',
        "name": 'Boyblanck',
        "spotify_id": '4ClQqb25PHO77Hciaauga5',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb2a58e29e5299b42dd55a65b9',
        "is_watched": 0,
    },
    {
        "id": 'ahmer',
        "name": 'Ahmer',
        "spotify_id": '0EAfS9gQe5SCtQp1R6hJqG',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb074160f2e4a3ed4c35d68ca9',
        "is_watched": 0,
    },
    {
        "id": 'gd-47',
        "name": 'GD 47',
        "spotify_id": '6uflkUXhbKhwVwZ3E2opoG',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb76dfa4f04c2c48a965d7b752',
        "is_watched": 0,
    },
    {
        "id": 'frappe-ash',
        "name": 'Frappe Ash',
        "spotify_id": '2dWPVvGGO8qRREfIwdXHZH',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb54b23a49ec5e725b3f3b607c',
        "is_watched": 0,
    },
    {
        "id": 'farak',
        "name": 'Farak',
        "spotify_id": '1gbYkP3zeoGen1itU6pO9a',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb9bcc6226aba2b75f3f390248',
        "is_watched": 0,
    },
    {
        "id": 'jaskaran',
        "name": 'Jaskaran',
        "spotify_id": '4AzMhFHYDgw1CZ9SIg885K',
        "youtube_channel_id": None,
        "genre": 'Punjabi/Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebf805bfedd2cd35a0c1b7f188',
        "is_watched": 0,
    },
    {
        "id": 'dopeadelicz',
        "name": 'Dopeadelicz',
        "spotify_id": '4HqaCsAhhMF8t4ExOwugpK',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebee87e3c523f08d16b75fd813',
        "is_watched": 0,
    },
    {
        "id": 'khasi-bloodz',
        "name": 'Khasi Bloodz',
        "spotify_id": '6Ym14v9LhQ6heQbUeTgzC8',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb2587d95fa27866b6ed6c7ddd',
        "is_watched": 0,
    },
    {
        "id": 'prathamesh',
        "name": 'Prathamesh',
        "spotify_id": '1s3KIr4EL3Qm033fYAn6sf',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb9e589267e2b18700ba887731',
        "is_watched": 0,
    },
    {
        "id": 'uniyal',
        "name": 'Uniyal',
        "spotify_id": '0EdBUkJHdLP4GGx3EN8AH0',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebb32380ddb095188d25933496',
        "is_watched": 0,
    },
    {
        "id": 'shreyas-sagvekar',
        "name": 'Shreyas Sagvekar',
        "spotify_id": '18EXRIpemLlnSLZPir6RCY',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab67616d0000b2736f4a22257ac53bd504eb23ed',
        "is_watched": 0,
    },
    {
        "id": 'raja-kumari',
        "name": 'Raja Kumari',
        "spotify_id": '5cBFMoMgcAt03YL2r0tS25',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb727df9daec6c6e9566696ab2',
        "is_watched": 0,
    },
    {
        "id": 'hardbone-boy',
        "name": 'Hardbone Boy',
        "spotify_id": '6YNVY8546Vw6bVjsmUpQPx',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb62190bae1156d272d0fa5867',
        "is_watched": 0,
    },
    {
        "id": 'khushi-tdt',
        "name": 'Khushi TDT',
        "spotify_id": '0O8DjpANOBrYwtNXlxbyff',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb7116a7b4f49bf080bc8d08a1',
        "is_watched": 0,
    },
    {
        "id": 'siri',
        "name": 'SIRI',
        "spotify_id": '41wifu6xToBViv1DGicbJj',
        "youtube_channel_id": None,
        "genre": 'Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb8b2681a0fbafd62424d64392',
        "is_watched": 0,
    },
    {
        "id": 'peter-cat-recording-co',
        "name": 'Peter Cat Recording Co.',
        "spotify_id": '41Nu7NgAj9rJxjj7JDuXrV',
        "youtube_channel_id": None,
        "genre": 'Indie',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb41bacc5ba605dfcc88c25733',
        "is_watched": 0,
    },
    {
        "id": 'the-f16s',
        "name": 'The F16s',
        "spotify_id": '5PVlXEAvlt6SfYpWBYTM4C',
        "youtube_channel_id": None,
        "genre": 'Indie Rock',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebcb0f64879d07b92658c97e1c',
        "is_watched": 0,
    },
    {
        "id": 'tejas',
        "name": 'Tejas',
        "spotify_id": '4CK1oDthUad8mQBb8GAcfl',
        "youtube_channel_id": None,
        "genre": 'Indie/Pop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb96b7f1e2e9df245e35c7108e',
        "is_watched": 0,
    },
    {
        "id": 'delhi-indie-project',
        "name": 'Delhi Indie Project',
        "spotify_id": '63lBPUJICXJ3HYgGR641M8',
        "youtube_channel_id": None,
        "genre": 'Indie Rock',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb2c80820e6ff6331f97ff7ade',
        "is_watched": 0,
    },
    {
        "id": 'raman-negi',
        "name": 'Raman Negi',
        "spotify_id": '1ZsF8DeNQav5xvu4X5KsYB',
        "youtube_channel_id": None,
        "genre": 'Indie',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb9ffbe7590616976a78401d80',
        "is_watched": 0,
    },
    {
        "id": 'justh',
        "name": 'Justh',
        "spotify_id": '6gxRXj2KUJ02vfIgkNUq5b',
        "youtube_channel_id": None,
        "genre": 'Indie',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb025bd33104bd3dca746e2653',
        "is_watched": 0,
    },
    {
        "id": 'mali',
        "name": 'Mali',
        "spotify_id": '4af9dUIG89GAuEsy6Se3F1',
        "youtube_channel_id": None,
        "genre": 'Indie/R&B',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb25c591cebdd1b8891d852dca',
        "is_watched": 0,
    },
    {
        "id": 'meba-ofilia',
        "name": 'Meba Ofilia',
        "spotify_id": '6mbXxVkhtdddGzR5yJ9SUD',
        "youtube_channel_id": None,
        "genre": 'R&B/Soul',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebb3cea6adddec0e711539fae5',
        "is_watched": 0,
    },
    {
        "id": 'kayan',
        "name": 'Kayan',
        "spotify_id": '3lfolnS8yn0VWK2FKM0hWs',
        "youtube_channel_id": None,
        "genre": 'Indie/Electronic',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb3915bd9db4a4e48cc245ab0d',
        "is_watched": 0,
    },
    {
        "id": 'gini',
        "name": 'GINI',
        "spotify_id": '2sjFmfxifbUo2A25xuQOp0',
        "youtube_channel_id": None,
        "genre": 'Indie Pop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb2567e4002ed6da6a68155755',
        "is_watched": 0,
    },
    {
        "id": 'parekh-and-singh',
        "name": 'Parekh & Singh',
        "spotify_id": '5HyacDSdBkCTDOBoX49ayp',
        "youtube_channel_id": None,
        "genre": 'Dream Pop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb078b425191810bb2ebc35018',
        "is_watched": 0,
    },
    {
        "id": 'injunktion',
        "name": 'Injunktion',
        "spotify_id": '0NkHkpGLND62hCDCdBkqKe',
        "youtube_channel_id": None,
        "genre": 'Indie/Funk',
        "image_url": 'https://i.scdn.co/image/ab67616d0000b273904311789b0605b67a1d3837',
        "is_watched": 0,
    },
    {
        "id": 'shantam',
        "name": 'Shantam',
        "spotify_id": '5MZxzsRwZLCey5qLcl82ar',
        "youtube_channel_id": None,
        "genre": 'Electronic',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb9ff7cbfc203b3509a27940c0',
        "is_watched": 0,
    },
    {
        "id": 'bombie',
        "name": 'BOMBIE',
        "spotify_id": None,
        "youtube_channel_id": None,
        "genre": 'Electronic',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb9d948b04d14193419ece22f3',
        "is_watched": 0,
    },
    {
        "id": 'kandy-kuri',
        "name": 'Kandy Kuri',
        "spotify_id": None,
        "youtube_channel_id": None,
        "genre": 'Electronic',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebaf20f7db5288bce9beede034',
        "is_watched": 0,
    },
    {
        "id": 'kratex',
        "name": 'Kratex',
        "spotify_id": '3Gowc3dedLQgQAt4y0gPBo',
        "youtube_channel_id": None,
        "genre": 'Electronic',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb09d10849a70c5e2d22eae8be',
        "is_watched": 0,
    },
    {
        "id": 'punch-m',
        "name": 'Punch M',
        "spotify_id": '2FgZrgTMX6Sk0VNcOsEPmm',
        "youtube_channel_id": None,
        "genre": 'Electronic',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb065608c797a38d142082fc8a',
        "is_watched": 0,
    },
    {
        "id": 'project-91',
        "name": 'Project 91',
        "spotify_id": '6HbsMua3wRqwv8WQRpbpYp',
        "youtube_channel_id": None,
        "genre": 'Electronic',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebece1e4d0c049123f7fae907c',
        "is_watched": 0,
    },
    {
        "id": 'prem-dhillon',
        "name": 'Prem Dhillon',
        "spotify_id": '6IP4VnqS1pOiQcPVP4zx0H',
        "youtube_channel_id": None,
        "genre": 'Punjabi',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb68d944e4bc03bcc85f4a2b90',
        "is_watched": 0,
    },
    {
        "id": 'mankirt-aulakh',
        "name": 'Mankirt Aulakh',
        "spotify_id": '3uHUKCspaCzAab9A3LlGAr',
        "youtube_channel_id": None,
        "genre": 'Punjabi',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5ebd4bc9e54d19e5f1e7930829a',
        "is_watched": 0,
    },
    {
        "id": 'dilpreet-dhillon',
        "name": 'Dilpreet Dhillon',
        "spotify_id": '5CGQa62CAweD76eHlDmp1m',
        "youtube_channel_id": None,
        "genre": 'Punjabi',
        "image_url": 'https://i.scdn.co/image/ab67616d0000b2734d6212c1d8b3717ec30edc5a',
        "is_watched": 0,
    },
    {
        "id": 'jordan-sandhu',
        "name": 'Jordan Sandhu',
        "spotify_id": '3TozxPbDes76aGFdfv7PMv',
        "youtube_channel_id": None,
        "genre": 'Punjabi',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb04423d2c30589421ce6cdf8c',
        "is_watched": 0,
    },
    {
        "id": 'nimrat-khaira',
        "name": 'Nimrat Khaira',
        "spotify_id": '0ea0y5ZxnN5TbEDzNtx5Fk',
        "youtube_channel_id": None,
        "genre": 'Punjabi',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb573396c5c4dc893a7363e128',
        "is_watched": 0,
    },
    {
        "id": 'singga',
        "name": 'Singga',
        "spotify_id": '6nmrEhAdodPuhMLMbefluW',
        "youtube_channel_id": None,
        "genre": 'Punjabi',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb1585ac8af1c3ae3fbb4c59f9',
        "is_watched": 0,
    },
    {
        "id": 'bohemia',
        "name": 'Bohemia',
        "spotify_id": '0SWOtgI95g7oVrP9halrmP',
        "youtube_channel_id": None,
        "genre": 'Punjabi/Hip-Hop',
        "image_url": 'https://i.scdn.co/image/ab6761610000e5eb786da5860b52e5395a3403e2',
        "is_watched": 0,
    },
    {
        "id": 'https://wwwyoutubecom/@sardarkhehra99',
        "name": 'https://www.youtube.com/@Sardarkhehra99',
        "spotify_id": None,
        "youtube_channel_id": None,
        "genre": 'Unknown',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'sardar-khehra',
        "name": 'sardar khehra',
        "spotify_id": None,
        "youtube_channel_id": None,
        "genre": 'Unknown',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'agsy',
        "name": 'Agsy',
        "spotify_id": None,
        "youtube_channel_id": 'UCB5zXRU4e6lVFQUKKXt1p3A',
        "genre": 'Unknown',
        "image_url": 'https://yt3.ggpht.com/EG4OP_fh95BRp9XNl8B_8ayn8xgCoxY6RugbPQ18KnF6GGO3ktNpvNeYJdf63iNTCpzc4g5G2A=s800-c-k-c0x00ffffff-no-rj',
        "is_watched": 1,
    },
    {
        "id": 'paradox',
        "name": 'Paradox',
        "spotify_id": None,
        "youtube_channel_id": 'UCf7fXrwR7c859zeHAsep6kw',
        "genre": 'Unknown',
        "image_url": 'https://yt3.ggpht.com/SqDgYGm8GGn_wJqgs7L5aHyLZhikrgHNq_D7IJiXpsbcPBURbNAJbJ4N0Hhj9N1U9gV0Fdth=s800-c-k-c0x00ffffff-no-rj',
        "is_watched": 0,
    },
    {
        "id": 'yung-sammy',
        "name": 'YUNG SAMMY',
        "spotify_id": None,
        "youtube_channel_id": 'UCO6UNMfe_Wn3PLLE8iKkYgA',
        "genre": 'Unknown',
        "image_url": 'https://yt3.ggpht.com/WUXL88U9ZWgZN0L82urDh_v7M5CcViL8Di11ZAcoDV-VTZ_yFra5j8WFHWbYGnxqFY78HXOFig=s800-c-k-c0x00ffffff-no-rj',
        "is_watched": 0,
    },
    {
        "id": 'darzi',
        "name": 'DARZI',
        "spotify_id": None,
        "youtube_channel_id": 'UCMFQCWcuz3EFzPEu1S9jZhg',
        "genre": 'Unknown',
        "image_url": 'https://yt3.ggpht.com/-7ILfHA4opcsDWzv4gr_-bPtRT7sbsU71JBxxA_bDCx1Hfc-xx4XSlrwOarji-N7vOdBA3N-0es=s800-c-k-c0x00ffffff-no-rj',
        "is_watched": 1,
    },
    {
        "id": 'lifafa',
        "name": 'LIFAFA',
        "spotify_id": None,
        "youtube_channel_id": 'UCYBh5kDH7w7pFeLiLMX6lkA',
        "genre": 'Unknown',
        "image_url": 'https://yt3.ggpht.com/IQAUWEowWyNG0u6l0BsbSx3DG6bM_lbGsTKiQXHDpnOdvi_1f-waSMCKMM6xAQiBYsuOO-1mJw=s800-c-k-c0x00ffffff-no-rj',
        "is_watched": 1,
    },
    {
        "id": 'fake-tattoos',
        "name": 'Fake Tattoos',
        "spotify_id": None,
        "youtube_channel_id": 'UC1MJLJwtQVeXb18Q_BaMVlA',
        "genre": 'Unknown',
        "image_url": 'https://yt3.ggpht.com/lQmInaNbMuX5HklUgvG3vT1fZB7EFNxPo2W5XaDk0ZkMc_QyV1TDdurXTaat8bwjyo3Lr7aR=s800-c-k-c0x00ffffff-no-rj',
        "is_watched": 0,
    },
    {
        "id": 'raghav-kaushik',
        "name": 'Raghav Kaushik',
        "spotify_id": None,
        "youtube_channel_id": 'UC4Wa41nr8IoimPjxyC6a5og',
        "genre": 'Unknown',
        "image_url": 'https://yt3.ggpht.com/20aTmBvtj--AGnBOb0MjuIo86-7ntogUOA9EOBv-Iph5zIdh9q-0QCTuS8HSMw0Y7tw9e7IUlA=s800-c-k-c0x00ffffff-no-rj',
        "is_watched": 0,
    },
    {
        "id": 'viepsa',
        "name": 'Viepsa',
        "spotify_id": None,
        "youtube_channel_id": 'UCewxoq4h7zuynmvyM5H3rYA',
        "genre": 'Unknown',
        "image_url": 'https://yt3.ggpht.com/i5yTGFZGMJUjeUHSaZ4nJq5zFHBJqXJWHXQU5bCCvbpXo7wor68d7o_qte6mE1Tgr2WJbWV2=s800-c-k-c0x00ffffff-no-rj',
        "is_watched": 1,
    },
    {
        "id": 'annural-khalid',
        "name": 'Annural Khalid',
        "spotify_id": None,
        "youtube_channel_id": 'UCEUor6AHCmZWwzxxUpne3Eg',
        "genre": 'Unknown',
        "image_url": 'https://yt3.ggpht.com/hS_DE4MZCZxaY4-BHJcWxyTUA8uxTBtVEqUwa9iSChsfRklTN9YQ12ORdYJFALV96HFJ4jfObA=s800-c-k-c0x00ffffff-no-rj',
        "is_watched": 0,
    },
    {
        "id": 'kavyaraag',
        "name": 'Kavyaraag',
        "spotify_id": None,
        "youtube_channel_id": 'UCRqeEt6ppTOtsZG6Y-GQMKg',
        "genre": 'Unknown',
        "image_url": 'https://yt3.ggpht.com/GAZxsisc1GGw14Hxj1WKH-KYMrF04ovtJDkgO-u9X8FlrDCBVrrXopUJejuRKo9vjtHTQgSp=s800-c-k-c0x00ffffff-no-rj',
        "is_watched": 0,
    },
    {
        "id": 'diljit-dosanjh',
        "name": 'Diljit Dosanjh',
        "spotify_id": '2FKWNmZWDBZR4qN7sec70O',
        "youtube_channel_id": 'UC0V69cU6Zqo5ILKA-vIsFmQ',
        "genre": 'Punjabi',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'sidhu-moose-wala',
        "name": 'Sidhu Moose Wala',
        "spotify_id": '4PULA4EFzYTrxYvOVlwpiQ',
        "youtube_channel_id": 'UCByOQJjav0CUDwxCk-jVNRQ',
        "genre": 'Punjabi',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'guru-randhawa',
        "name": 'Guru Randhawa',
        "spotify_id": '7qjJw7ts8h0aEhIRlJZfMj',
        "youtube_channel_id": 'UC4svjw4p4MmaSCCj7FpslKg',
        "genre": 'Punjabi',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'harrdy-sandhu',
        "name": 'Harrdy Sandhu',
        "spotify_id": '6qqNVTkY8uBg9cP3Jd7DAH',
        "youtube_channel_id": 'UCtgxVG4luB7of_S7S5rVEfQ',
        "genre": 'Punjabi',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'jassie-gill',
        "name": 'Jassie Gill',
        "spotify_id": '4JtnJHGFxxrQZn7YbZN27X',
        "youtube_channel_id": 'UC-L5lEd2KIGYW9bK6bESjqw',
        "genre": 'Punjabi',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'ammy-virk',
        "name": 'Ammy Virk',
        "spotify_id": '3Aiso4FMGU48djRgzJCUiy',
        "youtube_channel_id": 'UCqvv1N4TdIUvYfaFhJlOilQ',
        "genre": 'Punjabi',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'kaka',
        "name": 'Kaka',
        "spotify_id": '7wMDO4EvYfq0FWpuEqprro',
        "youtube_channel_id": 'UC80zt_U-1y-b5QKx7tkWdCQ',
        "genre": 'Punjabi',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'b-praak',
        "name": 'B Praak',
        "spotify_id": '1wRPtKGflJrBx9BmLsSwlU',
        "youtube_channel_id": 'UCclQoF69MNfV4E0hBh6JD-Q',
        "genre": 'Punjabi',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'mika-singh',
        "name": 'Mika Singh',
        "spotify_id": '4IJ7YGLdSRhWMVjGRFXZWM',
        "youtube_channel_id": 'UCiWKFYVMn_8cP3VIjAtIlQQ',
        "genre": 'Punjabi',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'badshah',
        "name": 'Badshah',
        "spotify_id": '0y59o4v8uw5crbN9M3JiL1',
        "youtube_channel_id": 'UCz7YuS1bITe7H2Bnb5VxHfQ',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'honey-singh',
        "name": 'Yo Yo Honey Singh',
        "spotify_id": '5B0XFxyUAocM9QIrVhupES',
        "youtube_channel_id": 'UCDsElQAt_pSTVsCJIzsTJkQ',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'raftaar',
        "name": 'Raftaar',
        "spotify_id": '4ZY8LkWE2FaDFVTVbu0VEf',
        "youtube_channel_id": 'UCfGseNfvkBkBjAeeQ7QK6uA',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'divine',
        "name": 'DIVINE',
        "spotify_id": '5f4QpKfy7ptCHwTqspnSJR',
        "youtube_channel_id": 'UCZzF1lnlIlZtMCHBY8cJIAQ',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'ikka',
        "name": 'Ikka',
        "spotify_id": '4EXe5QRonYFDyBz5RSPG7A',
        "youtube_channel_id": 'UCjGpVX3KaE-SbPJqGvBiNDw',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'seedhe-maut',
        "name": 'Seedhe Maut',
        "spotify_id": '5ffNpNbnbZFe5oKZagssdU',
        "youtube_channel_id": 'UCPIFKxnlMrmqA4uDYUaIAfA',
        "genre": 'Hip-Hop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'lucky-ali',
        "name": 'Lucky Ali',
        "spotify_id": '7bD54JOB3k8kI2h6FuOMPC',
        "youtube_channel_id": 'UCWLHgW0nTAhq1a8UlSvLN7g',
        "genre": 'Indie/Pop',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'papon',
        "name": 'Papon',
        "spotify_id": '0rqxICbgJKKdNlWP1kF2Nj',
        "youtube_channel_id": 'UCSzpGYxIllB4eBhYQ8WJLtA',
        "genre": 'Indie/Assamese',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'renuka-panwar',
        "name": 'Renuka Panwar',
        "spotify_id": '6P3FJt0zPbuGMa2agN1Oqb',
        "youtube_channel_id": 'UCiqkDpUR9Fb-3JUNbGPjjsA',
        "genre": 'Haryanvi',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'pawan-singh',
        "name": 'Pawan Singh',
        "spotify_id": '7iJrDbKM5fEkGdm5RO3dCn',
        "youtube_channel_id": 'UCW2NVP4SSkJiS-GVNc5CWMA',
        "genre": 'Bhojpuri',
        "image_url": None,
        "is_watched": 0,
    },
    {
        "id": 'khesari-lal',
        "name": 'Khesari Lal Yadav',
        "spotify_id": '3xT3GdBxhXJaAXSYPn5XXB',
        "youtube_channel_id": 'UCr0RYQY4QXTpBOe2g_MVrIg',
        "genre": 'Bhojpuri',
        "image_url": None,
        "is_watched": 0,
    },
]

def upsert_artist(conn, artist: dict):
    conn.execute(
        """INSERT INTO artists (id, name, spotify_id, youtube_channel_id, genre, image_url, is_watched)
           VALUES (?, ?, ?, ?, ?, ?, ?)
           ON CONFLICT(id) DO UPDATE SET
             name=excluded.name,
             spotify_id=excluded.spotify_id,
             youtube_channel_id=excluded.youtube_channel_id,
             genre=excluded.genre,
             image_url=excluded.image_url""",
        (
            artist["id"],
            artist["name"],
            artist.get("spotify_id"),
            artist.get("youtube_channel_id"),
            artist.get("genre"),
            artist.get("image_url"),
            artist.get("is_watched", 0),
        ),
    )
